version: '3.8'

services:
  sai-auth:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    container_name: sai-auth
    ports:
      - "${SERVER_EXTERNAL_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    networks:
      - sai-network
    restart: unless-stopped
    volumes:
      - ./config.template.yml:/app/config.template.yml


networks:
  sai-network:
    name: sai-network
    driver: bridge